services:
  otel-collector:
    image:  otel/opentelemetry-collector
    container_name: otel-collector
    ports:
      - "4318:4318"  
      - "9464:9464" 
      - "4317:4317"   
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml  
    command:
      - "--config=/etc/otel-collector-config.yml"
    networks:
      - obse-network



  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  
      - "14286:4317"    
      - "14250:14250"    

    networks:
      - obse-network
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./promethues.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
    restart: always
    ports:
      - '9091:9090'
    networks:
      - obse-network
    depends_on:
      - otel-collector

  grafana:
    container_name: grafana1
    image: arefobaid/grafana-custom
    restart: always
    ports:
      - '3000:3000'  # Grafana Web UI
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:465
      - GF_SMTP_USER=arefobaid7@gmail.com
      - GF_SMTP_PASSWORD=djfl loey mcta rmnw
      - GF_SMTP_FROM_ADDRESS=grafana@example.com
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Standard Admin Passwort
    volumes:
      - grafana-data:/var/lib/grafana
    
    networks:
      - obse-network

    depends_on:
      - prometheus

  loki:
    container_name: loki
    image: grafana/loki:3.0.0
    command: -config.file=/conf/loki-config.yml
    volumes:
      - ./loki:/conf
    ports:
     - "3100:3100" 
    networks:
      - obse-network



    
networks:
  obse-network:
    driver: bridge

    
volumes:
  grafana-data:
