receivers:
  otlp:
    protocols:
      grpc: # For receiving data via OTLP gRPC
        endpoint: "otel-collector:4317"
      http: # For receiving data via OTLP HTTP
        endpoint: "otel-collector:4318"
processors:
  batch:
  resource:
    attributes:
      - key: userservices
        action: upsert
        from_attribute: host.name

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "otel-collector:9464" 
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true



service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp] 
    metrics:
      receivers: [otlp]
      processors: [resource]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
