global:
  scrape_interval: 5s
  scrape_timeout: 5s
scrape_configs:
  - job_name: 'otel-collector'
    metrics_path: '/metrics'  
    static_configs:
      - targets: ['otel-collector:9464']
    honor_labels: true



  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'  
    static_configs:
      - targets: ['host.docker.internal:8080']


  - job_name: 'deliveryservice'
    metrics_path: '/actuator/prometheus'  
    static_configs:
      - targets: ['host.docker.internal:9098']


  - job_name: 'driverservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9099']




  - job_name: 'tracingservice'
    metrics_path: '/actuator/prometheus'  
    static_configs:
      - targets: ['host.docker.internal:9092']


  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'  
    static_configs:
      - targets: ['host.docker.internal:6060']


  - job_name: 'eurkadiscover'
    metrics_path: '/actuator/prometheus'  
    static_configs:
      - targets: ['host.docker.internal:9090']


